name: Log Timestamp Every Minute

on:
  schedule:
    - cron: "* * * * *"  # Every minute
  workflow_dispatch:

jobs:
  append_timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Pull latest changes
        run: git pull origin main  # replace 'main' if your default branch differs

      - name: Run timestamp script
        run: python update_time.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add timestamp.txt
          git commit -m "Append timestamp" || echo "Nothing to commit"
          git push
